// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNQciteMOP4YJBGwL6gARFIc_ZWjeE7FI',
    appId: '1:382582942143:web:9ac4b222d0a718ef36190a',
    messagingSenderId: '382582942143',
    projectId: 'auth-e8eda',
    authDomain: 'auth-e8eda.firebaseapp.com',
    storageBucket: 'auth-e8eda.appspot.com',
    measurementId: 'G-LL4300R7JB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc8NkydV7QqHAPoL--QjhSheA-GLvQA3A',
    appId: '1:382582942143:android:1d4edf8d3337f73136190a',
    messagingSenderId: '382582942143',
    projectId: 'auth-e8eda',
    storageBucket: 'auth-e8eda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEOBbF-RshPGEMAxjSRlyi0LiaQAwUVrA',
    appId: '1:382582942143:ios:0e78b6c0f9f9568336190a',
    messagingSenderId: '382582942143',
    projectId: 'auth-e8eda',
    storageBucket: 'auth-e8eda.appspot.com',
    iosBundleId: 'com.example.authApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEOBbF-RshPGEMAxjSRlyi0LiaQAwUVrA',
    appId: '1:382582942143:ios:bf25af75553ba72936190a',
    messagingSenderId: '382582942143',
    projectId: 'auth-e8eda',
    storageBucket: 'auth-e8eda.appspot.com',
    iosBundleId: 'com.example.authApp.RunnerTests',
  );
}
